# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/atom/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/atom-ims

PRODUCT_COPY_FILES += \
    vendor/xiaomi/atom-ims/proprietary/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.vtservice.rc

PRODUCT_PACKAGES += \
    libem_support_jni \
    libmtk_vt_wrapper \
    libmtkavenhancements \
    libmtkperf_client \
    libvcodec_cap \
    libvcodec_capenc \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libsignal \
    libsink \
    libsource \
    libvt_avsync \
    vendor.mediatek.hardware.videotelephony@1.0.system_ext \
    EngineerMode \
    ImsService \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    mediatek-ims-legacy \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    vtservice

PRODUCT_BOOT_JARS += \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \